DROP TABLE IF EXISTS events;

CREATE TABLE IF NOT EXISTS events
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app         VARCHAR(128)                            NOT NULL,
    uri         VARCHAR(255)                            NOT NULL,
    ip          VARCHAR(40)                             NOT NULL,
    timestamp   TIMESTAMP WITHOUT TIME ZONE             NOT NULL
);